
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lehmfhvdbakbcehxsenl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlaG1maHZkYmFrYmNlaHhzZW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTQ4MTQsImV4cCI6MjA2MTY5MDgxNH0.Fb_Aqi03vFD-scRl8i7YB8YtYGKsDboOSdNfsYjmPpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to fix type issues with Supabase Products table
export const getProductsTable = () => {
  return supabase.from('Products');
};

// Function to fix type issues with Supabase Orders table
export const getOrdersTable = () => {
  return supabase.from('Orders');
};
